//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Common;

namespace Generator
{
    public class GenerationManager
    {
        public virtual Function generate()
        {
            throw new System.NotImplementedException();
        }

        public virtual void saveToFile(Function f, string filename)
        {
            throw new System.NotImplementedException();
        }

    }
}
