//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Common;

namespace Generator
{
    public class Noiser
    {
        public virtual Function addNoise(Function f, INoise noise, double k)
        {
            Function result = new Function();
            result.setup(f.minX, f.maxX, f.step);
            for (int i = 0; i < f.length; i++)
                result[i] = f[i] + k * f[i] * noise.getDeviation();
            return result;
        }

    }
}
