//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Common;

namespace Generator
{
    public class Noiser
    {
        public virtual Function addNoise(Function f, INoise noise)
        {
            throw new System.NotImplementedException();
        }

    }
}
