//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows;

using Common;

namespace Processor
{
    public class ProcessingManager
    {
        public virtual Function loadFromFile(string filename)
        {
            throw new System.NotImplementedException();
        }

        public virtual UIElement process(Function f)
        {
            throw new System.NotImplementedException();
        }

    }
}
