//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using Common;

namespace Processor
{
    public abstract class ScalarProcessor : IProcessor
    {
        public abstract string title
        {
            get;
        }      
        public abstract string name { get; }
        public virtual UIElement process(Function f)
        {
            if (f == null) return null;

            Label result = new Label();
            result.Content = title + " = " + processFunction(f).ToString();

            return (UIElement)result;
        }

        public virtual void initialize()
        {
            return;
        }

        protected abstract double processFunction(Function f);

        public IList<Parameter> getParametersList()
        {
            return new List<Parameter>();
        }

        public void setup(IList<Object> parameters)
        {
            return;
        }

        public IList<string> checkParametersList(IList<Object> parameters)
        {
           return new List<string>();
        }

    }
}
