//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows;
using Common;

namespace Processor
{
    public abstract class ScalarProcessor : IProcessor
    {
        public abstract string title
        {
            get;
        }
        public virtual UIElement process(Function f)
        {
            throw new System.NotImplementedException();
        }

        public virtual void initialize()
        {
            throw new System.NotImplementedException();
        }

        protected abstract double processFunction(Function f);

        public IList<Parameter> getParametersList()
        {
            throw new System.NotImplementedException();
        }

        public void setup(IList<Object> parameters)
        {
            throw new System.NotImplementedException();
        }

        public bool checkParametersList(IList<Object> parameters)
        {
            throw new System.NotImplementedException();
        }

    }
}
