//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Processor;

namespace FourierTransformation
{
    public class FourierTransformation : ChartProcessor
    {
        public override string title
        {
            get { throw new NotImplementedException(); }
        }

        protected override Common.Function processFunction(Common.Function f)
        {
            throw new NotImplementedException();
        }
    }
}

