//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Processor;

namespace EnergyCalculation
{
    public class EnergyCalculation : ScalarProcessor
    {
        public override string title
        {
            get
            {
                return "Удельная энергия";
            }
        }
        public override string name
        {
            get
            {
                return "EnergyCalculation";
            }
        }     
 
        /// <summary>
        /// Вычисление интеграла
        /// </summary>
        /// <param name="f">Подинтегральная функция, возведенная в квадрат</param>
        /// <returns>Значение интеграла</returns>
        protected override double processFunction(Common.Function f)
        {
            throw new System.NotImplementedException();
        }
    }
}

