//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Processor;

namespace EnergyCalculation
{
    public class EnergyCalculation : ScalarProcessor
    {
        public override string title
        {
            get
            {
                throw new System.NotImplementedException();
            }
        }
        public override string name
        {
            get
            {
                throw new System.NotImplementedException();
            }
        }      

        protected override double processFunction(Common.Function f)
        {
            throw new NotImplementedException();
        }
    }
}

