//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Common
{
    public class CSVSerializer : ISerializer
    {
        public string title
        {
            get
            {
                throw new System.NotImplementedException();
            }
        }

        public string name
        {
            get
            {
                throw new System.NotImplementedException();
            }
        }

        public string extension { 
            get
            {
                throw new System.NotImplementedException();
            }
        }
        public virtual void serialize(Function f, string filename)
        {
            throw new System.NotImplementedException();
        }

        public virtual Function deserialize(string filename)
        {
            throw new System.NotImplementedException();
        }

        public virtual void initialize()
        {
            throw new System.NotImplementedException();
        }

        public IList<string> checkParametersList(IList<Object> parameters)
        {
            throw new System.NotImplementedException();
        }

        public void setup(IList<Object> parameters)
        {
            throw new System.NotImplementedException();
        }

        public IList<Parameter> getParametersList()
        {
            throw new System.NotImplementedException();
        }        
    }
}
