//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Common
{
    public class Function
    {
        public virtual double minX
        {
            get;
            private set;
        }

        public virtual double maxX
        {
            get;
            private set;
        }

        public virtual double step
        {
            get;
            private set;
        }

        public virtual double getValue(double x)
        {
            throw new System.NotImplementedException();
        }

        public virtual void setValue(double x, double value)
        {
            throw new System.NotImplementedException();
        }

        public virtual void setup(double minX, double maxX, double step)
        {
            throw new System.NotImplementedException();
        }

    }
}

