//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Common
{
    public interface IPlugin 
    {
        /// <summary>
        /// Описание плагина, которое выводится в UI
        /// </summary>
	    string title { get; }

        /// <summary>
        /// Уникальное внутреннее имя плагина
        /// </summary>
        string name { get; }   
     
        /// <summary>
        /// Вызывается каждый раз при инстанцировании плагина
        /// </summary>
	    void initialize();

        /// <summary>
        /// Возвращает список параметров, необходимых для его настройки
        /// </summary>
        /// <returns>Список параметров</returns>
	    IList<Parameter> getParametersList();

        /// <summary>
        /// Настраивает параметр соответствующими значениями параметров
        /// </summary>
        /// <param name="parameters">Параметры для настройки плагина</param>
	    void setup(IList<Object> parameters);

        /// <summary>
        /// Возвращает список ошибок
        /// </summary>
        /// <param name="parameters">Список параметров</param>
        /// <returns>Список описаний ошибок</returns>
	    IList<string> checkParametersList(IList<Object> parameters);

    }
}