//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Common
{
    public interface ISerializer : IPlugin
    {
        string extension { get; }

        void serialize(Function f, string filename);

        Function deserialize(string filename);

    }
}

