//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Common
{
    public class Parameter
    {
        public virtual Type type
        {
            get;
            private set;
        }

        public virtual string title
        {
            get;
            private set;
        }

        public virtual Object defaultValue
        {
            get;
            private set;
        }

        public Parameter(Type type, string title, Object defaultValue)
        {
        }

    }
}

