//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Common
{
    public class PluginManager
    {
        public virtual IList<IPlugin> getBeans(string interfaceName, string plaginName = null)
        {
            throw new System.NotImplementedException();
        }

        public virtual void refresh()
        {
            throw new System.NotImplementedException();
        }

    }
}
