//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Generator;
using Common;

namespace HarmonicFunctionGenerator
{     
    public class HarmonicFunctionGenerator : IGenerator
    {
        public string title
        {
            get
            {
                throw new System.NotImplementedException();
            }
        }
        public string name
        {
            get
            {
                throw new System.NotImplementedException();
            }
        }
        public virtual Function Generate(double minX, double maxX, double step)
	    {
		    throw new System.NotImplementedException();
	    }

	    public virtual IList<Parameter> getParametersList()
	    {
		    throw new System.NotImplementedException();
	    }

	    public virtual void setup(IList<Object> parameters)
	    {
		    throw new System.NotImplementedException();
	    }

	    public virtual void initialize()
	    {
		    throw new System.NotImplementedException();
	    }

        public bool checkParametersList(IList<Object> parameters)
        {
            throw new System.NotImplementedException();
        }
    }
}


