//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Common;
using Generator;


namespace UniformNoise
{
    /// <summary>
    /// Генератор равномерной случайной величены, с Мат. Ож. M=0 и Дисперсией D=1
    /// </summary>
    public class UniformNoise : INoise
    {
        /// <summary>
        /// Генератор псевдо случайных чисел
        /// </summary>
        private Random rand;

        public string title
        {
            get
            {
                return "Равномерная погрешность";
            }
        }
        public string name
        {
            get
            {
                return "UniformNoise";
            }
        }
        
        /// <summary>
        /// Генерирует равномерную случайную величену
        /// </summary>
        /// <returns>Случайную величену</returns>
	    public virtual double getDeviation()
	    {
            return (rand.NextDouble() * 2 - 1) * Math.Sqrt(3);
	    }

        /// <summary>
        /// Возвращает список параметров равномерного распределения
        /// </summary>
        /// <returns>Список параметров</returns>
	    public virtual IList<Parameter> getParametersList()
	    {
            List<Parameter> p = new List<Parameter>();
            return p;
	    }

        /// <summary>
        /// Инициализирует параметры
        /// </summary>
        /// <param name="parameters">Список параметров</param>
	    public virtual void setup(IList<Object> parameters)
	    {
            //throw new ArgumentException("Not available argument");
	    }

        /// <summary>
        /// Инициализирует генератор псевдо случайных велечин
        /// </summary>
	    public virtual void initialize()
	    {
            rand = new Random();
	    }

        /// <summary>
        /// Проверяет подходят ли параметры для данного модуля
        /// </summary>
        /// <param name="parameters">Список параметров</param>
        /// <returns>Успех / ошибка</returns>
        public IList<string> checkParametersList(IList<Object> parameters)
        {
            //TODO: нужно возвращать список описаний ошибок
            throw new System.NotImplementedException();

            /*
            if (parameters.Count != 0)
                return false;
            return true;
             */
        }
    }
}

