//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Common;
using Generator;


namespace UniformNoise
{
    public class UniformNoise : INoise
    {
        private Random rand;    //pseudo-random number generator

        public string title
        {
            get
            {
                return "Равномерная погрешность";
            }
        }
        public string name
        {
            get
            {
                return "UniformNoise";
            }
        }
	    public virtual double getDeviation()
	    {
            return (rand.NextDouble() * 2 - 1) * Math.Sqrt(3);
	    }

	    public virtual IList<Parameter> getParametersList()
	    {
            List<Parameter> p = new List<Parameter>();
            return null;
	    }

	    public virtual void setup(IList<Object> parameters)
	    {
            //throw new ArgumentException("Not available argument");
	    }

	    public virtual void initialize()
	    {
            rand = new Random();
	    }

        public bool checkParametersList(IList<Object> parameters)
        {
            if (parameters.Count != 0)
                return false;
            return true;
        }
    }
}

